### PR TITLE
fix: change link to completed event detail to summary

### LINKED ISSUE #2106: When viewing the completed event list/map on the home page, clicking on the event should probably take the user to the event summary page, not the event details page.

### PR DESCRIPTION
**Pull request by pitipatdop**
Fix #2106 

Other fixes:
- Remove type definition `DisplayEvent`

### CODE REVIEW

File: TrashMob/client-app/src/lib/event-helpers.ts [hunk 1]
```diff
@@ -0,0 +1,10 @@
+/**
+ * A utility & helper function for event
+ */
+
+import EventData from '@/components/Models/EventData';
+import moment from 'moment';
+
+export const isCompletedEvent = (event: EventData) => {
+    return moment(event.eventDate).isBefore();
```
Comment (joebeernink) [inline TrashMob/client-app/src/lib/event-helpers.ts:9]: Should this be eventDate+eventdurationhours+eventdurationminutes?

Comment (pitipatdop) [reply TrashMob/client-app/src/lib/event-helpers.ts:9]: That is true, will fix

**Review by joebeernink — APPROVED** [review]
